### ISSUE TITLE
Compatibility with Python 3.11 typing system is wonky

### ISSUE THREAD

**Issue by tungalbert99** [sander76/clipstick#30]
Something like the below works: 
```
description: Optional[str] = None 
``` 
Something like the below doesn't work (supported by 3.11 which is equivalent) 
```
description: str | None = None
```
which throws the error `ERROR: A union composing a subcommand must all be of type BaseModel`

**Comment by tungalbert99** [comment]
https://github.com/sander76/clipstick/pull/32 addressed here

**Comment by sander76** [comment]
thanks for the fix!
