### ISSUE TITLE
[feature] Nested Models support

### ISSUE THREAD

**Issue by tungalbert99** [sander76/clipstick#31]
Nested models require a dictionary which cannot be parsed via command line

**Comment by sander76** [comment]
that's true. that's one of the design decisions I made: As far as I see a nested model does not match the structure of a "traditional" cli (like argparse or click), which is the target outcome of this library.

[tyro](https://github.com/brentyi/tyro) does have this capability, but as a result is more complex. Both in defining your models as in providing arguments.

**Comment by tungalbert99** [comment]
that is fair, up to your design! I still find it useful to have some hierarchy in configurations that are preserved by pydantic

**Comment by sander76** [comment]
If you come up with an idea of doing this without adding a lot more complexity, you're more than welcome.
